name: null

channels:
  - conda-forge
  - defaults

dependencies:
  - pytables==3.6.1
  - pandas==1.0.3
  - fast-histogram==0.8
  - hurry.filesize==0.9
  - defusedxml==0.6.0
  - mysql-connector-python==8.0.15
  - astropy==3.2.3
